;;; -*- lexical-binding: t -*-
(setq custom-file "~/.emacs.d/custom.el")
(push (expand-file-name "lisp/" user-emacs-directory) load-path)
(push (expand-file-name "lisp/lang" user-emacs-directory) load-path)
(dolist (entry (directory-files-and-attributes
                (expand-file-name "extension" user-emacs-directory) t "\\`[^.]"))
  (when (eq t (cadr entry))
    (push (car entry) load-path)))

(put 'if-let 'byte-obsolete-info nil)
(put 'when-let 'byte-obsolete-info nil)
(package-initialize)
(require 'cl-lib)
(require 'init-def)
(require 'init-font)
(require 'init-display)
(require 'init-base)
(require 'init-advanced)
(require 'init-editor)
(require 'init-lang)
(require 'init-debug)
(require 'init-diagnostics)
(require 'init-completion)
(require 'init-navigation)
(require 'init-vc)
(require 'init-www)
(require 'init-utils)
(require 'init-mode-line)
(require 'init-terminal)
(require 'init-keybind)
(require 'init-word-move)
(require 'init-context-menu)
(require 'init-home)
(require 'nn-world-theme)
(load custom-file)
