;;; -*- lexical-binding: t -*-
(setq custom-file (expand-file-name "custom.el" user-emacs-directory))
(let ((file-name-handler-alist nil))
  (require 'nn-world-theme)
  (require 'init-def)
  (load custom-file)
  (when (display-graphic-p)
    (require 'init-font))
  (require 'init-base)
  (require 'init-advanced)
  (require 'init-display)
  (require 'init-editor)
  (require 'init-lang)
  (require 'init-debug)
  (require 'init-diagnostics)
  (require 'init-completion)
  (require 'init-navigation)
  (require 'init-vc)
  (require 'init-www)
  (require 'init-utils)
  (require 'init-mode-line)
  (require 'init-terminal)
  (require 'init-keybind)
  (require 'init-word-move)
  (require 'init-context-menu)
  (require 'init-home))
