;;; -*- lexical-binding: t -*-
(defun my-cut ()
  (interactive)
  (if (use-region-p)
      (kill-region (region-beginning) (region-end))
    (kill-whole-line)))

(defun my-copy ()
  (interactive)
  (if (use-region-p)
      (copy-region-as-kill (region-beginning) (region-end))
    (progn (kill-ring-save (line-beginning-position) (line-beginning-position 2)))))

(defun my-move-line-up ()
  (interactive)
  (transpose-lines 1)
  (forward-line -2))

(defun my-move-line-down ()
  (interactive)
  (forward-line 1)
  (transpose-lines 1)
  (forward-line -1))

(defun my-copy-line-and-move-down ()
  (interactive)
  (duplicate-line)
  (next-line 1))

(defun my-delete-whole-line-no-kill ()
  (interactive)
  (delete-region (line-beginning-position) (line-beginning-position 2)))

(defun my-kill ()
  (interactive)
  (when (and (buffer-file-name)
             (file-exists-p (buffer-file-name))
             (buffer-modified-p))
    (save-buffer))
  (kill-current-buffer))

(defun my-downcase-dwim ()
  (interactive)
  (if (use-region-p)
      (downcase-region (region-beginning) (region-end))
    (call-interactively #'downcase-word)))

(defun my-upcase-dwim ()
  (interactive)
  (if (use-region-p)
      (upcase-region (region-beginning) (region-end))
    (call-interactively #'upcase-word)))

(defun my-home-dired ()
  (interactive)
  (dired "~"))

(defun my-switch-to-project-root ()
  (interactive)
  (if-let* ((proj (project-current)))
      (dired (project-root proj))
    (dired default-directory)))

(defun my-surround-word (char)
  (interactive "cWrap char: ")
  (when-let (bnd (bounds-of-thing-at-point 'word))
    (save-excursion
      (goto-char (cdr bnd)) (insert char)
      (goto-char (car bnd)) (insert char))))

(defun my-surround-replace (char)
  (interactive "cReplace surrounding chars with: ")
  (when-let ((bounds (bounds-of-thing-at-point 'word)))
    (save-excursion
      (goto-char (car bounds))
      (when (search-backward-regexp "[^[:space:]]" (line-beginning-position) t)
        (delete-char 1) (insert char))
      (goto-char (cdr bounds))
      (when (search-forward-regexp "[^[:space:]]" (line-end-position) t)
        (delete-char -1) (insert char)))))

(defun my-surround-replace-pair (old-char new-char)
  (interactive "cWrap char? \ncReplace surrounding chars with: ")
  (when-let ((bounds (bounds-of-thing-at-point 'word)))
    (save-excursion
      (goto-char (car bounds))
      (when (search-backward (string old-char) (line-beginning-position) t)
        (delete-char 1)
        (insert (string new-char)))
      (goto-char (cdr bounds))
      (when (search-forward (string old-char) (line-end-position) t)
        (delete-char -1)
        (insert (string new-char))))))

(defun my-replace-string-whole-buffer (from to)
  (interactive "sReplace: \nsWith: ")
  (save-excursion
    (replace-string from to nil (point-min) (point-max))))

(defun my-split-and-switch (direction)
  (let ((buf (read-buffer
              "Switch to buffer: "
              (other-buffer (current-buffer) t))))
    (pcase direction
      ('right (select-window (split-window-right)))
      ('below (select-window (split-window-below)))
      ('left  (split-window-right))
      ('above (split-window-below)))
    (switch-to-buffer buf)))

(defun my-split-right-and-switch ()  (interactive) (my-split-and-switch 'right))
(defun my-split-left-and-switch  ()  (interactive) (my-split-and-switch 'left))
(defun my-split-below-and-switch ()  (interactive) (my-split-and-switch 'below))
(defun my-split-above-and-switch ()  (interactive) (my-split-and-switch 'above))
(keymap-global-set "C-c o f" #'my-split-right-and-switch)
(keymap-global-set "C-c o b" #'my-split-left-and-switch)
(keymap-global-set "C-c o n" #'my-split-below-and-switch)
(keymap-global-set "C-c o p" #'my-split-above-and-switch)
(keymap-global-set "C-c o <right>" #'my-split-right-and-switch)
(keymap-global-set "C-c o <left>" #'my-split-left-and-switch)
(keymap-global-set "C-c o <down>" #'my-split-below-and-switch)
(keymap-global-set "C-c o <up>" #'my-split-above-and-switch)
(keymap-global-set "C-!" #'my-replace-string-whole-buffer)
(keymap-global-set "M-S-<right>" #'shrink-window-horizontally)
(keymap-global-set "M-S-<left>" #'enlarge-window-horizontally)
(keymap-global-set "M-S-<down>" #'shrink-window)
(keymap-global-set "M-S-<up>" #'enlarge-window)
(keymap-global-set "C-!" #'my-replace-string-whole-buffer)
(keymap-global-set "C-c w r" #'my-surround-replace)
(keymap-global-set "C-c w R" #'my-surround-replace-pair)
(keymap-global-set "C-c w w" #'my-surround-word)
(keymap-global-set "C-c C-r" #'my-switch-to-project-root)
(keymap-global-set "M-l" #'my-downcase-dwim)
(keymap-global-set "M-u" #'my-upcase-dwim)
(keymap-global-set "M-<up>" #'my-move-line-up)
(keymap-global-set "M-<down>" #'my-move-line-down)
(keymap-global-set "M-w" #'my-copy)
(keymap-global-set "C-w" #'my-cut)
(keymap-global-set "C-x k" #'my-kill)
(keymap-global-set "C-x C-k" #'kill-buffer)
(keymap-global-set "C-S-<backspace>" #'my-delete-whole-line-no-kill)
(keymap-global-set "C-," #'my-copy-line-and-move-down)
(keymap-global-set "C-~" #'my-home-dired)
(keymap-global-set "C-'" #'imenu)
(keymap-global-set "C-1" #'scroll-up-command)
(keymap-global-set "C-2" #'scroll-down-command)
(keymap-global-set "C-3" #'recenter-top-bottom)
(keymap-global-set "C-M-<up>" #'windmove-up)
(keymap-global-set "C-M-<down>" #'windmove-down)
(keymap-global-set "C-M-<left>" #'windmove-left)
(keymap-global-set "C-M-<right>" #'windmove-right)
(keymap-global-set "M-<f11>" #'toggle-frame-fullscreen)
(keymap-global-set "<escape>" #'keyboard-escape-quit)
(keymap-global-set "S-<tab>" #'indent-rigidly-left-to-tab-stop)
(keymap-global-set "C-<tab>" #'bs-cycle-next)
(keymap-global-set "C-S-<tab>" #'bs-cycle-previous)
(keymap-global-set "C-a" #'back-to-indentation)
(keymap-global-set "C-v" #'yank)
(keymap-global-set "C-z" #'undo)
(keymap-global-set "C-S-z" #'undo-redo)

(provide 'init-keybind)
