;;; nn-world-theme.el --- Custom dark theme -*- lexical-binding: t; -*-

(require 'color)

(deftheme nn-world)

(defun nn-world-reload ()
  (interactive)
  (disable-theme 'nn-world)
  (load-theme 'nn-world t))

(let ((bg           "#1a1a1e")
      (fg           "#cccccc")
      (bright       "#8a8a8a")
      (dim          "#6a6a6a")
      (secondary    "#4a4a4a")
      (tertiary     "#2a2a2a")
      (quaternary   "#1a1a1a")
      (pink         "#f0b0e0")
      (red          "#f38ba8")
      (orange       "#f5a97f")
      (yellow       "#eed49f")
      (green        "#a6da95")
      (teal         "#4ec9b0")
      (blue         "#89b4fa")
      (purple       "#b180d7")
      (gold         "#b8860b")
      (red-dark     "#f44747")
      (red-deep     "#5a1d1d")
      (yellow-dark  "#eecc00")
      (green-dark   "#52ab52")
      (green-deep   "#2a4a2a")
      (blue-muted   "#7da6e0")
      (purple-muted "#c586c0"))
  (custom-theme-set-faces
   'nn-world
   `(default        ((t :background ,bg :foreground ,fg)))
   `(success        ((t :foreground ,green)))
   `(warning        ((t :foreground ,yellow-dark)))
   `(error          ((t :foreground ,red-dark)))
   `(match          ((t :background ,red :foreground ,red-deep :bold t)))
   `(shadow         ((t :foreground ,bright)))
   `(border         ((t :background ,pink)))
   `(highlight      ((t :background ,secondary)))
   `(lazy-highlight ((t :inherit highlight)))
   `(region         ((t :background ,(color-lighten-name secondary 20))))

   `(vertical-border            ((t :foreground ,bright)))
   `(window-divider             ((t :inherit vertical-border)))
   `(window-divider-first-pixel ((t :inherit window-divider)))
   `(window-divider-last-pixel  ((t :inherit window-divider)))

   `(delete-selection-replacement ((t :inherit nil)))
   `(child-frame-border           ((t :inherit border)))

   `(fringe                 ((t :background ,bg)))
   `(secondary-selection    ((t :background ,secondary :foreground ,fg)))
   `(header-line            ((t :background ,tertiary :foreground ,fg)))
   `(mode-line              ((t :background ,tertiary :foreground ,fg)))
   `(mode-line-inactive     ((t :background ,tertiary :foreground ,bright)))
   `(minibuffer-prompt      ((t :foreground ,pink)))
   `(minibuffer-nonselected ((t :inherit error)))
   `(escape-glyph           ((t :foreground ,yellow)))
   `(homoglyph              ((t :foreground ,yellow)))
   `(tooltip                ((t :background ,quaternary :foreground ,fg)))
   `(help-key-binding       ((t :inherit tooltip)))

   `(button                 ((t (:underline t))))
   `(icon-button            ((t (:box (:line-width 2 :color ,bright)))))
   `(custom-button          ((t (:box (:line-width 2 :color ,bright)))))
   `(custom-button-mouse    ((t (:inherit highlight :box (:line-width 2 :color ,bright)))))
   `(custom-button-unraised ((t (:underline t))))
   `(widget-field           ((t (:background ,secondary))))

   `(cursor         ((t :background ,pink)))
   `(mc/cursor-face ((t :inherit cursor)))

   `(link         ((t :underline t)))
   `(link-visited ((t :inherit default :underline t)))

   `(line-number              ((t :inherit default :foreground ,bright)))
   `(line-number-current-line ((t :inherit line-number :foreground ,pink)))

   `(show-paren-match            ((t :box (:line-width (-1 . -1) :color ,pink))))
   `(show-paren-match-expression ((t :inherit match)))
   `(show-paren-mismatch         ((t :inherit warning)))

   `(whitespace-big-indent       ((t :foreground ,orange)))
   `(whitespace-empty            ((t :inherit warning)))
   `(whitespace-indentation      ((t :foreground ,tertiary)))
   `(whitespace-line             ((t :underline (:style wave :color ,gold))))
   `(whitespace-newline          ((t :foreground ,dim)))
   `(whitespace-space            ((t :foreground ,dim :inherit italic)))
   `(whitespace-space-after-tab  ((t :inherit warning)))
   `(whitespace-space-before-tab ((t :inherit warning)))
   `(whitespace-tab              ((t :inherit whitespace-newline)))
   `(whitespace-trailing         ((t :foreground ,orange :background ,orange)))
   `(trailing-whitespace         ((t :inherit whitespace-trailing)))

   `(font-lock-bracket-face              ((t :foreground ,fg)))
   `(font-lock-builtin-face              ((t :foreground ,red)))
   `(font-lock-comment-face              ((t :foreground ,green-dark)))
   `(font-lock-comment-delimiter-face    ((t :inherit font-lock-comment-face)))
   `(font-lock-constant-face             ((t :foreground ,yellow)))
   `(font-lock-delimiter-face            ((t :foreground ,bright)))
   `(font-lock-escape-face               ((t :foreground ,bright)))
   `(font-lock-function-name-face        ((t :foreground ,purple :inherit italic)))
   `(font-lock-keyword-face              ((t :foreground ,pink :inherit italic)))
   `(font-lock-negation-char-face        ((t :foreground ,red)))
   `(font-lock-number-face               ((t :foreground ,orange)))
   `(font-lock-operator-face             ((t :foreground ,blue)))
   `(font-lock-preprocessor-face         ((t :foreground ,bright)))
   `(font-lock-property-name-face        ((t :foreground ,blue)))
   `(font-lock-reference-face            ((t :foreground ,yellow)))
   `(font-lock-regexp-grouping-backslash ((t :foreground ,orange)))
   `(font-lock-regexp-grouping-construct ((t :foreground ,orange)))
   `(font-lock-string-face               ((t :foreground ,green)))
   `(font-lock-type-face                 ((t :foreground ,purple-muted :inherit italic)))
   `(font-lock-variable-name-face        ((t :foreground ,fg)))
   `(font-lock-variable-use-face         ((t :foreground ,fg)))

   `(isearch      ((t :inherit match)))
   `(isearch-fail ((t :inherit error)))

   `(ido-first-match       ((t :foreground ,yellow)))
   `(ido-only-match        ((t :foreground ,green)))
   `(ido-subdir            ((t :inherit dired-directory)))
   `(ido-virtual           ((t :foreground ,blue)))
   `(ido-incomplete-regexp ((t :inherit warning)))
   `(ido-indicator         ((t :foreground ,fg :weight bold)))

   `(rg-filename-face       ((t :inherit font-lock-string-face)))
   `(rg-file-tag-face       ((t :foreground ,yellow)))
   `(rg-line-number-face    ((t :foreground ,orange)))
   `(rg-match-face          ((t :inherit highlight)))
   `(rg-match-position-face ((t :inherit line-number)))
   `(rg-literal-face        ((t :foreground ,pink)))
   `(rg-regexp-face         ((t :foreground ,orange)))
   `(rg-error-face          ((t :inherit error)))
   `(rg-warning-face        ((t :inherit warning)))
   `(rg-info-face           ((t :inherit compilation-info)))
   `(rg-toggle-on-face      ((t :foreground ,bright)))
   `(rg-toggle-off-face     ((t :foreground ,bright)))

   `(wgrep-face        ((t nil)))
   `(wgrep-done-face   ((t :inherit success :strike-through t)))
   `(wgrep-reject-face ((t :inherit error :underline (:style wave))))

   `(newsticker-treeview-selection-face ((t :foreground ,pink :bold t)))

   `(dired-flagged           ((t :foreground ,red)))
   `(dired-marked            ((t :bold t)))
   `(dired-mark              ((t :inherit dired-marked)))
   `(dired-header            ((t :foreground ,pink)))
   `(dired-ignored           ((t :foreground ,dim)))
   `(dired-special           ((t :foreground ,yellow)))
   `(dired-symlink           ((t :foreground ,pink)))
   `(dired-warning           ((t :inherit warning)))
   `(dired-directory         ((t :foreground ,fg)))
   `(dired-perm-write        ((t :foreground ,green)))
   `(dired-broken-symlink    ((t :foreground ,fg :background ,red)))

   `(speedbar-button-face    ((t :foreground ,teal)))
   `(speedbar-directory-face ((t :inherit dired-directory)))
   `(speedbar-file-face      ((t :foreground ,fg)))
   `(speedbar-highlight-face ((t :inherit highlight)))
   `(speedbar-selected-face  ((t :foreground ,pink :underline t)))
   `(speedbar-separator-face ((t :foreground ,dim)))
   `(speedbar-tag-face       ((t :foreground ,yellow)))

   `(flymake-error   ((t :underline (:style wave :color ,red-dark))))
   `(flymake-warning ((t :underline (:style wave :color ,yellow-dark))))
   `(flymake-note    ((t :underline (:style dots :color ,bright))))

   `(eglot-semantic-defaultLibrary ((t nil)))
   `(eglot-semantic-namespace      ((t :inherit font-lock-type-face)))

   `(eglot-diagnostic-tag-deprecated-face  ((t :foreground ,dim :strike-through t)))
   `(eglot-diagnostic-tag-unnecessary-face ((t :background ,tertiary
                                               :foreground ,secondary
                                               :inherit flymake-warning)))
   `(eglot-highlight-symbol-face           ((t :inherit lazy-highlight)))
   `(eglot-inlay-hint-face                 ((t :foreground ,green-dark :italic t)))
   `(eglot-mode-line                       ((t :foreground ,fg)))
   `(eglot-parameter-hint-face             ((t :foreground ,teal)))
   `(eglot-type-hint-face                  ((t :foreground ,green)))

   `(dape-breakpoint-face                ((t :inherit error :bold t)))
   `(dape-breakpoint-until-face          ((t :background ,yellow)))
   `(dape-exception-description-face     ((t :inherit error)))
   `(dape-expression-face                ((t :inherit font-lock-string-face)))
   `(dape-header-line-active-face        ((t :inherit minibuffer-prompt :bold t)))
   `(dape-header-line-hover-face         ((t :inherit highlight)))
   `(dape-header-line-inactive-face      ((t :inherit shadow)))
   `(dape-hits-face                      ((t :inherit success :bold t)))
   `(dape-inlay-hint-face                ((t :background ,tertiary :foreground ,dim)))
   `(dape-inlay-hint-highlight-face      ((t :background ,secondary :foreground ,blue :bold t)))
   `(dape-log-face                       ((t :inherit shadow)))
   `(dape-minibuffer-hint-separator-face ((t :inherit shadow)))
   `(dape-repl-error-face                ((t :inherit error)))
   `(dape-source-line-face               ((t :background ,red-deep)))

   `(eldoc-box-border ((t :inherit border)))
   `(eldoc-box-body   ((t :inherit tooltip)))

   `(completions-annotations      ((t :foreground ,bright)))
   `(completions-common-part      ((t :foreground ,pink)))
   `(completions-first-difference ((t :foreground ,pink)))
   `(completions-group-separator  ((t :foreground ,dim :strike-through t)))
   `(completions-group-title      ((t :foreground ,pink :bold t)))
   `(completions-highlight        ((t :inherit highlight)))

   `(completion-preview-exact ((t :foreground ,bright)))

   `(corfu-default     ((t :inherit tooltip)))
   `(corfu-current     ((t :inherit highlight)))
   `(corfu-border      ((t :inherit border)))
   `(corfu-deprecated  ((t :inherit completions-group-separator)))

   `(calfw-toolbar-face            ((t :background ,pink)))
   `(calfw-title-face              ((t :foreground ,red :height 2.5 :bold t)))
   `(calfw-grid-face               ((t :foreground ,purple :bold t)))
   `(calfw-toolbar-button-on-face  ((t :background ,tertiary :foreground ,fg :bold t)))
   `(calfw-toolbar-button-off-face ((t :foreground ,quaternary :bold t)))

   `(diff-header            ((t :foreground ,red)))
   `(diff-file-header       ((t :foreground ,yellow)))
   `(diff-added             ((t :background ,green-deep)))
   `(diff-removed           ((t :background ,red-deep)))
   `(diff-indicator-added   ((t :inherit diff-added :foreground ,green)))
   `(diff-indicator-removed ((t :inherit diff-removed :foreground ,red)))

   `(vc-state-base            ((t :foreground ,fg)))
   `(vc-up-to-date-state      ((t :foreground ,green)))
   `(vc-edited-state          ((t :foreground ,yellow)))
   `(vc-needs-update-state    ((t :foreground ,orange)))
   `(vc-locked-state          ((t :foreground ,orange)))
   `(vc-locally-added-state   ((t :foreground ,green)))
   `(vc-conflict-state        ((t :inherit error)))
   `(vc-removed-state         ((t :inherit error)))
   `(vc-missing-state         ((t :inherit error)))
   `(vc-ignored-state         ((t :foreground ,purple-muted)))
   `(vc-dir-header            ((t :foreground ,pink)))
   `(vc-dir-header-value      ((t :foreground ,fg)))
   `(vc-dir-directory         ((t :inherit dired-directory)))
   `(vc-dir-file              ((t :foreground ,fg)))
   `(vc-dir-mark-indicator    ((t :foreground ,yellow)))
   `(vc-dir-status-warning    ((t :inherit warning)))
   `(vc-dir-status-edited     ((t :foreground ,yellow)))
   `(vc-dir-status-up-to-date ((t :foreground ,green)))
   `(vc-dir-status-ignored    ((t :foreground ,dim)))

   `(git-commit-summary               ((t :foreground ,fg)))
   `(git-commit-overlong-summary      ((t :foreground ,red :underline t)))
   `(git-commit-nonempty-second-line  ((t :foreground ,red :bold t)))
   `(git-commit-keyword               ((t :foreground ,blue)))
   `(git-commit-comment-heading       ((t :foreground ,dim)))
   `(git-commit-comment-file          ((t :foreground ,yellow)))
   `(git-commit-comment-branch-local  ((t :foreground ,green)))
   `(git-commit-comment-branch-remote ((t :foreground ,pink)))
   `(git-commit-comment-detached      ((t :foreground ,orange)))
   `(git-commit-comment-action        ((t :foreground ,green)))
   `(git-commit-trailer-token         ((t :foreground ,purple)))
   `(git-commit-trailer-value         ((t :foreground ,blue)))

   `(magit-branch-local                ((t :foreground ,pink)))
   `(magit-branch-remote               ((t :foreground ,green)))
   `(magit-tag                         ((t :foreground ,orange)))
   `(magit-section-heading             ((t :foreground ,pink)))
   `(magit-diff-context-highlight      ((t :foreground ,fg :extend t)))
   `(magit-diff-revision-summary       ((t :foreground ,blue)))
   `(magit-diff-added                  ((t :inherit diff-added)))
   `(magit-diff-removed                ((t :inherit diff-removed)))
   `(magit-diff-file-heading           ((t :foreground ,pink)))
   `(magit-diffstat-added              ((t :foreground ,green)))
   `(magit-diffstat-removed            ((t :foreground ,red)))
   `(magit-diff-hunk-heading           ((t :foreground ,fg)))
   `(magit-diff-hunk-heading-highlight ((t :bold t)))
   `(magit-diff-file-heading-selection ((t :inherit highlight)))
   `(magit-magit-section-highlight     ((t :inherit highlight)))
   `(magit-hash                        ((t :foreground ,bright)))
   `(magit-log-author                  ((t :foreground ,red)))
   `(magit-process-ng                  ((t :foreground ,orange :bold t)))
   `(magit-process-ok                  ((t :foreground ,green :bold t)))

   `(compilation-error          ((t :inherit error)))
   `(compilation-warning        ((t :inherit warning)))
   `(compilation-info           ((t :inherit success)))
   `(compilation-line-number    ((t :foreground ,yellow-dark)))
   `(compilation-column-number  ((t :foreground ,yellow-dark)))
   `(compilation-mode-line-exit ((t :foreground ,green)))
   `(compilation-mode-line-fail ((t :foreground ,red)))
   `(compilation-mode-line-run  ((t :foreground ,yellow-dark)))

   `(eshell-ls-archive    ((t :foreground ,gold)))
   `(eshell-ls-backup     ((t :foreground ,yellow)))
   `(eshell-ls-clutter    ((t :foreground ,red :bold t)))
   `(eshell-ls-directory  ((t :foreground ,secondary :bold t)))
   `(eshell-ls-executable ((t :foreground ,green :bold t)))
   `(eshell-ls-missing    ((t :foreground ,red :bold t)))
   `(eshell-ls-product    ((t :foreground ,orange)))
   `(eshell-ls-readonly   ((t :foreground ,red)))
   `(eshell-ls-special    ((t :foreground ,pink :bold t)))
   `(eshell-ls-symlink    ((t :foreground ,blue :bold t)))
   `(eshell-prompt        ((t :foreground ,pink)))

   `(rainbow-delimiters-depth-1-face   ((t :foreground ,yellow)))
   `(rainbow-delimiters-depth-2-face   ((t :foreground ,pink)))
   `(rainbow-delimiters-depth-3-face   ((t :foreground ,blue-muted)))
   `(rainbow-delimiters-depth-4-face   ((t :foreground ,orange)))
   `(rainbow-delimiters-depth-5-face   ((t :foreground ,purple-muted)))
   `(rainbow-delimiters-depth-6-face   ((t :foreground ,green)))
   `(rainbow-delimiters-depth-7-face   ((t :foreground ,teal)))
   `(rainbow-delimiters-depth-8-face   ((t :foreground ,gold)))
   `(rainbow-delimiters-unmatched-face ((t :inherit warning)))

   `(indent-bars-1 ((t :foreground ,red)))
   `(indent-bars-2 ((t :foreground ,orange)))
   `(indent-bars-3 ((t :foreground ,yellow)))
   `(indent-bars-4 ((t :foreground ,green)))
   `(indent-bars-5 ((t :foreground ,teal)))
   `(indent-bars-6 ((t :foreground ,blue)))
   `(indent-bars-7 ((t :foreground ,purple)))
   `(indent-bars-8 ((t :foreground ,pink)))
   `(indent-bars-9 ((t :foreground ,red)))

   `(symbol-overlay-face-1       ((t :foreground ,yellow :inverse-video t)))
   `(symbol-overlay-face-2       ((t :foreground ,pink :inverse-video t)))
   `(symbol-overlay-face-3       ((t :foreground ,blue-muted :inverse-video t)))
   `(symbol-overlay-face-4       ((t :foreground ,orange :inverse-video t)))
   `(symbol-overlay-face-5       ((t :foreground ,purple-muted :inverse-video t)))
   `(symbol-overlay-face-6       ((t :foreground ,green :inverse-video t)))
   `(symbol-overlay-face-7       ((t :foreground ,teal :inverse-video t)))
   `(symbol-overlay-face-8       ((t :foreground ,gold :inverse-video t)))
   `(symbol-overlay-default-face ((t :inherit highlight)))

   `(outline-1 ((t :foreground ,red)))
   `(outline-2 ((t :foreground ,orange)))
   `(outline-3 ((t :foreground ,yellow)))
   `(outline-4 ((t :foreground ,green)))
   `(outline-5 ((t :foreground ,teal)))
   `(outline-6 ((t :foreground ,blue)))
   `(outline-7 ((t :foreground ,purple)))

   `(message-header-to         ((t :foreground ,red)))
   `(message-header-cc         ((t :foreground ,bright)))
   `(message-header-subject    ((t :foreground ,purple)))
   `(message-header-newsgroups ((t :foreground ,secondary)))
   `(message-header-other      ((t :foreground ,green)))
   `(message-header-name       ((t :foreground ,pink)))
   `(message-header-xheader    ((t :foreground ,secondary)))
   `(message-separator         ((t :inherit font-lock-comment-face)))
   `(message-cited-text        ((t :foreground ,secondary)))
   `(message-cited-text-1      ((t :foreground ,red)))
   `(message-cited-text-2      ((t :foreground ,orange)))
   `(message-cited-text-3      ((t :foreground ,yellow)))
   `(message-cited-text-4      ((t :foreground ,green)))
   `(message-mml               ((t :foreground ,blue :underline t)))

   `(ansi-color-black          ((t :foreground ,dim)))
   `(ansi-color-red            ((t :foreground ,red)))
   `(ansi-color-yellow         ((t :foreground ,yellow)))
   `(ansi-color-green          ((t :foreground ,green)))
   `(ansi-color-blue           ((t :foreground ,blue)))
   `(ansi-color-magenta        ((t :foreground ,purple)))
   `(ansi-color-cyan           ((t :foreground ,teal)))
   `(ansi-color-white          ((t :foreground ,secondary)))
   `(ansi-color-bright-black   ((t :foreground ,dim)))
   `(ansi-color-bright-red     ((t :foreground ,red :bold t)))
   `(ansi-color-bright-yellow  ((t :foreground ,yellow :bold t)))
   `(ansi-color-bright-green   ((t :foreground ,green :bold t)))
   `(ansi-color-bright-blue    ((t :foreground ,blue :bold t)))
   `(ansi-color-bright-magenta ((t :foreground ,pink :bold t)))
   `(ansi-color-bright-cyan    ((t :foreground ,teal :bold t)))
   `(ansi-color-bright-white   ((t :foreground ,fg :bold t)))

   `(shr-h1             ((t :bold t :height 1.4 :foreground ,fg)))
   `(shr-h2             ((t :bold t :height 1.3 :foreground ,fg)))
   `(shr-h3             ((t :bold t :height 1.2 :foreground ,fg)))
   `(shr-h4             ((t :bold t :height 1.1 :foreground ,fg)))
   `(shr-h5             ((t :bold t :height 1.0 :foreground ,fg)))
   `(shr-h6             ((t :bold t :height 0.9 :foreground ,fg)))
   `(shr-link           ((t :foreground ,blue)))
   `(shr-selected-link  ((t :foreground ,purple :underline t)))
   `(shr-code           ((t :foreground ,teal :background ,tertiary)))
   `(shr-mark           ((t :background ,yellow)))
   `(shr-abbreviation   ((t :underline t)))
   `(shr-strike-through ((t :foreground ,red :strike-through t :bold t)))
   `(shr-sup            ((t :height 0.8)))

   `(web-mode-doctype-face                   ((t :inherit font-lock-builtin-face)))
   `(web-mode-html-tag-face                  ((t :inherit font-lock-keyword-face)))
   `(web-mode-html-tag-bracket-face          ((t :inherit font-lock-delimiter-face)))
   `(web-mode-html-tag-custom-face           ((t :inherit font-lock-constant-face)))
   `(web-mode-html-tag-namespaced-face       ((t :inherit font-lock-escape-face)))
   `(web-mode-html-tag-unclosed-face         ((t :foreground ,red :underline t)))
   `(web-mode-html-attr-name-face            ((t :foreground ,yellow)))
   `(web-mode-html-attr-value-face           ((t :inherit font-lock-string-face)))
   `(web-mode-html-attr-equal-face           ((t :foreground ,fg)))
   `(web-mode-html-attr-custom-face          ((t :foreground ,teal)))
   `(web-mode-html-attr-engine-face          ((t :foreground ,yellow)))
   `(web-mode-html-entity-face               ((t :foreground ,orange)))
   `(web-mode-css-property-name-face         ((t :inherit font-lock-type-face)))
   `(web-mode-css-selector-face              ((t :inherit font-lock-function-name-face)))
   `(web-mode-css-selector-class-face        ((t :inherit web-mode-css-selector-face)))
   `(web-mode-css-selector-tag-face          ((t :inherit web-mode-css-selector-face)))
   `(web-mode-css-pseudo-class-face          ((t :inherit font-lock-type-face)))
   `(web-mode-css-priority-face              ((t :foreground ,orange)))
   `(web-mode-css-function-face              ((t :foreground ,yellow)))
   `(web-mode-css-variable-face              ((t :foreground ,teal)))
   `(web-mode-css-at-rule-face               ((t :inherit font-lock-keyword-face)))
   `(web-mode-css-color-face                 ((t :foreground ,orange)))
   `(web-mode-css-string-face                ((t :inherit font-lock-string-face)))
   `(web-mode-css-comment-face               ((t :inherit font-lock-comment-face)))
   `(web-mode-javascript-string-face         ((t :inherit font-lock-string-face)))
   `(web-mode-javascript-comment-face        ((t :inherit font-lock-comment-face)))
   `(web-mode-json-key-face                  ((t :foreground ,teal)))
   `(web-mode-json-string-face               ((t :inherit font-lock-string-face)))
   `(web-mode-json-context-face              ((t :foreground ,fg)))
   `(web-mode-json-comment-face              ((t :inherit font-lock-comment-face)))
   `(web-mode-sql-keyword-face               ((t :inherit font-lock-keyword-face)))
   `(web-mode-jsx-depth-1-face               ((t :background ,red)))
   `(web-mode-jsx-depth-2-face               ((t :background ,orange)))
   `(web-mode-jsx-depth-3-face               ((t :background ,yellow)))
   `(web-mode-jsx-depth-4-face               ((t :background ,green)))
   `(web-mode-jsx-depth-5-face               ((t :background ,teal)))
   `(web-mode-block-delimiter-face           ((t :foreground ,fg)))
   `(web-mode-block-control-face             ((t :inherit font-lock-keyword-face)))
   `(web-mode-block-comment-face             ((t :inherit font-lock-comment-face)))
   `(web-mode-block-string-face              ((t :inherit font-lock-string-face)))
   `(web-mode-block-attr-name-face           ((t :foreground ,teal)))
   `(web-mode-block-attr-value-face          ((t :inherit font-lock-string-face)))
   `(web-mode-comment-keyword-face           ((t :inherit font-lock-comment-face)))
   `(web-mode-comment-face                   ((t :inherit font-lock-comment-face)))
   `(web-mode-string-face                    ((t :inherit font-lock-string-face)))
   `(web-mode-keyword-face                   ((t :inherit font-lock-keyword-face)))
   `(web-mode-builtin-face                   ((t :inherit font-lock-builtin-face)))
   `(web-mode-constant-face                  ((t :inherit font-lock-constant-face)))
   `(web-mode-type-face                      ((t :inherit font-lock-type-face)))
   `(web-mode-function-name-face             ((t :inherit font-lock-function-name-face)))
   `(web-mode-function-call-face             ((t :inherit font-lock-function-call-face)))
   `(web-mode-variable-name-face             ((t :inherit font-lock-variable-name-face)))
   `(web-mode-param-name-face                ((t :inherit font-lock-variable-name-face)))
   `(web-mode-number-face                    ((t :inherit font-lock-number-face)))
   `(web-mode-operator-face                  ((t :inherit font-lock-operator-face)))
   `(web-mode-preprocessor-face              ((t :inherit font-lock-preprocessor-face)))
   `(web-mode-error-face                     ((t :inherit error)))
   `(web-mode-warning-face                   ((t :inherit warning)))
   `(web-mode-symbol-face                    ((t :inherit font-lock-constant-face)))
   `(web-mode-filter-face                    ((t :inherit font-lock-keyword-face)))
   `(web-mode-inlay-face                     ((t :background ,tertiary)))
   `(web-mode-annotation-face                ((t :foreground ,bright)))
   `(web-mode-annotation-tag-face            ((t :inherit font-lock-keyword-face)))
   `(web-mode-annotation-html-face           ((t :foreground ,teal)))
   `(web-mode-annotation-type-face           ((t :inherit font-lock-type-face)))
   `(web-mode-annotation-value-face          ((t :inherit font-lock-string-face)))
   `(web-mode-part-face                      ((t :foreground ,fg)))
   `(web-mode-part-comment-face              ((t :inherit font-lock-comment-face)))
   `(web-mode-part-string-face               ((t :inherit font-lock-string-face)))
   `(web-mode-style-face                     ((t :foreground ,fg)))
   `(web-mode-script-face                    ((t :foreground ,fg)))
   `(web-mode-whitespace-face                ((t :foreground ,dim)))
   `(web-mode-folded-face                    ((t :underline t)))
   `(web-mode-bold-face                      ((t :bold t)))
   `(web-mode-italic-face                    ((t :italic t)))
   `(web-mode-underline-face                 ((t :underline t)))
   `(web-mode-block-face                     ((t :background ,tertiary)))
   `(web-mode-interpolate-color1-face        ((t :foreground ,red)))
   `(web-mode-interpolate-color2-face        ((t :foreground ,orange)))
   `(web-mode-interpolate-color3-face        ((t :foreground ,yellow)))
   `(web-mode-interpolate-color4-face        ((t :foreground ,green)))
   `(web-mode-current-element-highlight-face ((t :background ,secondary)))
   `(web-mode-current-column-highlight-face  ((t :background ,tertiary)))

   `(org-level-1                   ((t :foreground ,pink :bold t :height 1.4)))
   `(org-level-2                   ((t :foreground ,purple :bold t :height 1.3)))
   `(org-level-3                   ((t :foreground ,purple-muted :bold t :height 1.2)))
   `(org-level-4                   ((t :foreground ,blue-muted :height 1.1)))
   `(org-level-5                   ((t :foreground ,orange :height 1.0)))
   `(org-level-6                   ((t :foreground ,bright :height 0.9)))
   `(org-level-7                   ((t :foreground ,bright :height 0.8)))
   `(org-level-8                   ((t :foreground ,dim :height 0.7)))
   `(org-code                      ((t :foreground ,green)))
   `(org-verbatim                  ((t :foreground ,purple-muted)))
   `(org-link                      ((t :foreground ,blue-muted :underline t)))
   `(org-block                     ((t :extend t :foreground ,fg :background ,tertiary)))
   `(org-block-begin-line          ((t :foreground ,bright)))
   `(org-block-end-line            ((t :inherit org-block-begin-line)))
   `(org-quote                     ((t :foreground ,purple-muted :slant italic)))
   `(org-table                     ((t :foreground ,blue-muted)))
   `(org-checkbox                  ((t :foreground ,teal)))
   `(org-list-dt                   ((t :foreground ,purple)))
   `(org-todo                      ((t :foreground ,pink :bold t)))
   `(org-done                      ((t :foreground ,green)))
   `(org-headline-done             ((t :inherit org-done)))
   `(org-date                      ((t :foreground ,bright)))
   `(org-tag                       ((t :foreground ,bright)))
   `(org-priority                  ((t :foreground ,pink :bold t)))
   `(org-warning                   ((t :foreground ,red :bold t)))
   `(org-hide                      ((t :foreground ,bg)))
   `(org-indent                    ((t :foreground ,bg)))
   `(org-ellipsis                  ((t :inherit font-lock-comment-face)))
   `(org-meta-line                 ((t :foreground ,green)))
   `(org-document-title            ((t :foreground ,pink :bold t)))
   `(org-document-info             ((t :foreground ,red)))
   `(org-document-info-keyword     ((t :inherit font-lock-keyword-face)))
   `(org-footnote                  ((t :foreground ,orange)))
   `(org-formula                   ((t :foreground ,orange)))
   `(org-special-keyword           ((t :inherit font-lock-keyword-face)))
   `(org-latex-and-related         ((t :foreground ,orange)))
   `(org-macro                     ((t :foreground ,bright)))
   `(org-hr                        ((t :foreground ,dim)))
   `(org-agenda-date-today         ((t :foreground ,pink :bold t)))
   `(org-agenda-date-weekend       ((t :foreground ,bright)))
   `(org-agenda-date-weekend-today ((t :foreground ,pink :bold t)))
   `(org-agenda-dimmed-todo-face   ((t :inherit font-lock-comment-face)))
   `(org-agenda-done               ((t :foreground ,green)))
   `(org-agenda-structure          ((t :foreground ,pink :bold t)))
   `(org-scheduled                 ((t :foreground ,bright)))
   `(org-scheduled-previously      ((t :foreground ,red)))
   `(org-scheduled-today           ((t :foreground ,pink :bold t)))
   `(org-sexp-date                 ((t :foreground ,bright)))
   `(org-upcoming-deadline         ((t :foreground ,red :bold t)))

   `(markdown-blockquote-face         ((t :foreground ,purple-muted)))
   `(markdown-bold-face               ((t :foreground ,pink :bold t)))
   `(markdown-italic-face             ((t :slant italic :foreground ,fg)))
   `(markdown-strike-through-face     ((t :strike-through t :foreground ,dim)))
   `(markdown-markup-face             ((t :foreground ,bright)))
   `(markdown-inline-code-face        ((t :foreground ,green)))
   `(markdown-highlight-face          ((t :inherit highlight)))
   `(markdown-header-face-1           ((t :foreground ,pink :bold t :height 1.4)))
   `(markdown-header-face-2           ((t :foreground ,purple :bold t :height 1.3)))
   `(markdown-header-face-3           ((t :foreground ,purple-muted :bold t :height 1.2)))
   `(markdown-header-face-4           ((t :foreground ,blue-muted :height 1.1)))
   `(markdown-header-face-5           ((t :foreground ,purple-muted :height 1.0)))
   `(markdown-header-face-6           ((t :foreground ,bright :height 0.9)))
   `(markdown-header-delimiter-face   ((t :foreground ,dim)))
   `(markdown-header-rule-face        ((t :foreground ,dim)))
   `(markdown-code-face               ((t :extend t :foreground ,fg :background ,tertiary)))
   `(markdown-pre-face                ((t :foreground ,fg)))
   `(markdown-language-keyword-face   ((t :foreground ,bright)))
   `(markdown-language-info-face      ((t :foreground ,bright)))
   `(markdown-link-face               ((t :foreground ,blue-muted :underline t)))
   `(markdown-url-face                ((t :foreground ,green :underline t)))
   `(markdown-plain-url-face          ((t :foreground ,blue-muted :underline t)))
   `(markdown-link-title-face         ((t :foreground ,orange)))
   `(markdown-missing-link-face       ((t :foreground ,red-dark :underline t)))
   `(markdown-reference-face          ((t :foreground ,secondary)))
   `(markdown-list-face               ((t :foreground ,teal)))
   `(markdown-gfm-checkbox-face       ((t :foreground ,teal)))
   `(markdown-table-face              ((t :foreground ,fg)))
   `(markdown-footnote-marker-face    ((t :foreground ,orange)))
   `(markdown-footnote-text-face      ((t :foreground ,orange)))
   `(markdown-metadata-key-face       ((t :foreground ,bright)))
   `(markdown-metadata-value-face     ((t :foreground ,bright)))
   `(markdown-hr-face                 ((t :foreground ,dim)))
   `(markdown-line-break-face         ((t :foreground ,dim)))
   `(markdown-comment-face            ((t :foreground ,bright)))
   `(markdown-html-attr-name-face     ((t :inherit font-lock-constant-face)))
   `(markdown-html-attr-value-face    ((t :foreground ,green)))
   `(markdown-html-entity-face        ((t :foreground ,orange)))
   `(markdown-html-tag-delimiter-face ((t :inherit font-lock-delimiter-face)))
   `(markdown-html-tag-name-face      ((t :inherit font-lock-keyword-face)))
   `(markdown-math-face               ((t :foreground ,orange)))

   `(markdown-ts-bold                             ((t :foreground ,pink :bold t)))
   `(markdown-ts-emphasis                         ((t :slant italic :foreground ,fg)))
   `(markdown-ts-strikethrough                    ((t :strike-through t :foreground ,dim)))
   `(markdown-ts-delimiter                        ((t nil)))
   `(markdown-ts-code-span                        ((t :foreground ,green)))
   `(markdown-ts-code-block                       ((t :extend t :foreground ,fg :background ,tertiary)))
   `(markdown-ts-in-code-block                    ((t :foreground ,teal :background ,tertiary)))
   `(markdown-ts-indented-code-block              ((t :foreground ,green)))
   `(markdown-ts-language-keyword                 ((t :foreground ,bright)))
   `(markdown-ts-heading-1                        ((t :foreground ,pink :bold t :height 1.4)))
   `(markdown-ts-heading-2                        ((t :foreground ,purple :bold t :height 1.3)))
   `(markdown-ts-heading-3                        ((t :foreground ,purple-muted :bold t :height 1.2)))
   `(markdown-ts-heading-4                        ((t :foreground ,blue-muted :height 1.1)))
   `(markdown-ts-heading-5                        ((t :foreground ,purple-muted :height 1.0)))
   `(markdown-ts-heading-6                        ((t :foreground ,bright :height 0.9)))
   `(markdown-ts-link                             ((t :foreground ,blue-muted :underline t)))
   `(markdown-ts-link-destination                 ((t :foreground ,green :underline t)))
   `(markdown-ts-list-marker                      ((t :foreground ,teal)))
   `(markdown-ts-block-quote                      ((t :foreground ,purple-muted)))
   `(markdown-ts-html-block                       ((t :foreground ,purple-muted)))
   `(markdown-ts-table                            ((t :foreground ,fg)))
   `(markdown-ts-table-cell                       ((t :foreground ,fg)))
   `(markdown-ts-table-header                     ((t :foreground ,fg)))
   `(markdown-ts-table-delimiter-cell             ((t :foreground ,fg)))
   `(markdown-ts-in-table                         ((t :foreground ,fg)))
   `(markdown-ts-html-tag                         ((t :inherit font-lock-keyword-face)))
   `(markdown-ts-latex                            ((t :foreground ,orange)))
   `(markdown-ts-thematic-break                   ((t :foreground ,dim)))
   `(markdown-ts-task-checked                     ((t :foreground ,teal)))
   `(markdown-ts-task-unchecked                   ((t :foreground ,teal)))
   `(markdown-ts-entity-reference                 ((t :foreground ,orange)))
   `(markdown-ts-numeric-character-reference      ((t :foreground ,orange)))
   `(markdown-ts-hard-line-break-space            ((t :foreground ,dim)))
   `(markdown-ts-hard-line-break-backslash        ((t :foreground ,dim)))
   `(markdown-ts-hard-line-break-space-hidden     ((t :foreground ,dim)))
   `(markdown-ts-hard-line-break-backslash-hidden ((t :foreground ,dim)))
   `(markdown-ts-code-block-markup-hidden         ((t :foreground ,bright)))
   `(markdown-ts-setext-heading                   ((t :foreground ,pink :bold t)))

   `(gnus-cite-1                 ((t :foreground ,bright)))
   `(gnus-cite-2                 ((t :foreground ,bright)))
   `(gnus-cite-3                 ((t :foreground ,bright)))
   `(gnus-cite-4                 ((t :foreground ,bright)))
   `(gnus-cite-5                 ((t :foreground ,bright)))
   `(gnus-cite-6                 ((t :foreground ,bright)))
   `(gnus-cite-7                 ((t :foreground ,bright)))
   `(gnus-cite-8                 ((t :foreground ,bright)))
   `(gnus-cite-9                 ((t :foreground ,bright)))
   `(gnus-cite-10                ((t :foreground ,bright)))
   `(gnus-cite-11                ((t :foreground ,bright)))
   `(gnus-cite-attribution       ((t :foreground ,bright)))
   `(gnus-header                 ((t :foreground ,fg :bold t)))
   `(gnus-header-from            ((t :foreground ,fg :bold t)))
   `(gnus-header-subject         ((t :foreground ,fg :bold t)))
   `(gnus-header-newsgroups      ((t :foreground ,purple)))
   `(gnus-header-name            ((t :foreground ,pink)))
   `(gnus-header-content         ((t :foreground ,fg)))
   `(gnus-summary-normal-unread  ((t :foreground ,pink :bold t)))
   `(gnus-summary-normal-read    ((t :foreground ,bright)))
   `(gnus-summary-normal-ancient ((t :foreground ,dim)))
   `(gnus-summary-normal-ticked  ((t :foreground ,purple-muted)))
   `(gnus-summary-high-unread    ((t :foreground ,pink :bold t)))
   `(gnus-summary-high-read      ((t :foreground ,secondary)))
   `(gnus-summary-high-ancient   ((t :foreground ,dim)))
   `(gnus-summary-high-ticked    ((t :foreground ,secondary)))
   `(gnus-summary-low-unread     ((t :foreground ,purple-muted)))
   `(gnus-summary-low-read       ((t :foreground ,bright)))
   `(gnus-summary-low-ancient    ((t :foreground ,dim)))
   `(gnus-summary-low-ticked     ((t :foreground ,purple-muted)))
   `(gnus-summary-selected       ((t :foreground ,fg :background ,secondary :bold t)))
   `(gnus-summary-cancelled      ((t :foreground ,dim :strike-through t)))
   `(gnus-group-mail-1           ((t :foreground ,yellow :bold t)))
   `(gnus-group-mail-2           ((t :foreground ,pink :bold t)))
   `(gnus-group-mail-3           ((t :foreground ,blue-muted)))
   `(gnus-group-mail-4           ((t :foreground ,orange)))
   `(gnus-group-mail-5           ((t :foreground ,purple-muted)))
   `(gnus-group-mail-6           ((t :foreground ,green)))
   `(gnus-group-mail-low         ((t :foreground ,teal)))
   `(gnus-group-mail-1-empty     ((t :foreground ,bright :italic t)))
   `(gnus-group-mail-2-empty     ((t :foreground ,bright :italic t)))
   `(gnus-group-mail-3-empty     ((t :foreground ,bright :italic t)))
   `(gnus-group-mail-4-empty     ((t :foreground ,bright :italic t)))
   `(gnus-group-mail-5-empty     ((t :foreground ,bright :italic t)))
   `(gnus-group-mail-6-empty     ((t :foreground ,bright :italic t)))
   `(gnus-group-mail-low-empty   ((t :foreground ,dim :italic t)))
   `(gnus-group-news-1           ((t :foreground ,pink :bold t)))
   `(gnus-group-news-2           ((t :foreground ,purple :bold t)))
   `(gnus-group-news-3           ((t :foreground ,purple-muted)))
   `(gnus-group-news-4           ((t :foreground ,blue-muted)))
   `(gnus-group-news-5           ((t :foreground ,teal)))
   `(gnus-group-news-6           ((t :foreground ,bright)))
   `(gnus-group-news-low         ((t :foreground ,dim)))
   `(gnus-server-opened          ((t :foreground ,green)))
   `(gnus-server-closed          ((t :foreground ,red-dark)))
   `(gnus-server-denied          ((t :foreground ,red-dark)))
   `(gnus-server-offline         ((t :foreground ,dim)))
   `(gnus-server-agent           ((t :foreground ,secondary)))
   `(gnus-server-cloud           ((t :foreground ,secondary)))
   `(gnus-server-cloud-host      ((t :foreground ,dim)))
   `(gnus-signature              ((t :foreground ,dim :slant italic)))
   `(gnus-button                 ((t :foreground ,blue-muted :underline t)))
   `(gnus-emphasis-bold          ((t :bold t)))
   `(gnus-emphasis-italic        ((t :slant italic)))
   `(gnus-emphasis-underline     ((t :underline t)))
   `(gnus-splash                 ((t :foreground ,dim)))))

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'nn-world)
;;; nn-world-theme.el ends here
